version: '3'
services:
  db:
    container_name: rails-db
    image: mysql:8.0.35
    environment:
      MYSQL_USER: dbuser
      MYSQL_ROOT_PASSWORD: dbpassword
    ports:
      - 3306:3306
    volumes:
      - mysql_db_volume:/var/lib/mysql

  app:
    container_name: rails-app
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/app
      - rails_gem_volume:/usr/local/bundle
    ports:
      - 8000:3000
    depends_on:
      - db
  


volumes:
  mysql_db_volume:
  rails_gem_volume: